apiVersion: v1
data:
  DB_ENGINE: postgresql
  DB_PORT: "5432"
  DB_POOL_SIZE: "5"
  DB_POOL_MAX_OVERFLOW: "2"
  DB_POOL_RECYCLE: "3600"
  DB_POOL_TIMEOUT: "30"
  DB_HOST: playground-db.postgres.database.azure.com
  DB_NAME: dev
  DB_USER: wfadmin
  REDIS_HOST: pg.redis.cache.windows.net
  REDIS_PORT: "6380"
  REDIS_USE_SSL: "True"
kind: ConfigMap
metadata:
  name: infra-config
  namespace: dev