apiVersion: v1
data:
  traefik.yml: |-
    ################################################################
    # Global configuration
    global:
      checkNewVersion: true
      sendAnonymousUsage: true

    ################################################################
    # EntryPoints configuration
    entryPoints:
      web:
        address: :8000

    ################################################################
    # Traefik logs configuration
    log:
      level: DEBUG
      # filePath: /mnt/data/tax/logs/gateway/traefik.log

    ################################################################
    # Access logs configuration
    accessLog:
      addInternals: true
      filePath: /mnt/data/tax/logs/gateway/traefik_access.log
      format: json

    ################################################################
    # API and dashboard configuration
    api:
      insecure: true

    ################################################################
    # Provider configuration
    providers:
      file:
        filename: /etc/config/dynamic_conf.yml
kind: ConfigMap
metadata:
  name: gateway-cm
  namespace: tax

