apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
    project: agent
  name: gateway
  namespace: agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
      project: agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
        project: agent
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: WORKER
          value: "2"
        envFrom:
        - configMapRef:
            name: common-cm
        - configMapRef:
            name: infra-cm
        - configMapRef:
            name: ai-cm
        - secretRef:
            name: common-secret
        image: traefik:v3.1
        imagePullPolicy: IfNotPresent
        name: gateway
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8080
          name: dashboard
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/data
          name: data
        - mountPath: /etc/config/dynamic_conf.yml
          name: dynamic-conf
          subPath: dynamic_conf.yml
        - mountPath: /etc/traefik/traefik.yml
          name: conf
          subPath: traefik.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: agent-account
      serviceAccountName: agent-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: agent-file-pvc
      - configMap:
          defaultMode: 420
          name: gateway-dynamic-conf-cm
        name: dynamic-conf
      - configMap:
          defaultMode: 420
          name: gateway-cm
        name: conf
