apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: chat
  sessionAffinity: None
  type: ClusterIP