apiVersion: v1
kind: Service
metadata:
  name: llm-gateway-svc
  namespace: dev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: llm-gateway
  sessionAffinity: None
  type: ClusterIP