apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phoenix
    project: agent
  name: phoenix
  namespace: agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: phoenix
      project: agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phoenix
        project: agent
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PHOENIX_WORKING_DIR
          value: "/mnt/data/agent/phoenix"
        image: arizephoenix/phoenix:version-11.7.0
        imagePullPolicy: IfNotPresent
        name: phoenix
        ports:
        - containerPort: 6006
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6006
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: agent-account
      serviceAccountName: agent-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: agent-file-pvc