apiVersion: v1
kind: Service
metadata:
  labels:
    app: phoenix
    project: agent
  name: phoenix-svc
  namespace: agent
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 6006
    protocol: TCP
    targetPort: 6006
  selector:
    app: phoenix
    project: agent
  sessionAffinity: None
  type: ClusterIP
